/*
 * Copyright 2015-2025 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {PluginSpecification} from '@valtimo/plugin';
import {ROTTERDAM_ORACLE_EBS_PLUGIN_LOGO_BASE64} from './assets';
import {ConfigurationComponent} from "./components/configuration/configuration.component";
import {JournaalpostOpvoerenComponent} from "./components/journaalpost-opvoeren/journaalpost-opvoeren.component";
import {VerkoopfactuurOpvoerenComponent} from "./components/verkoopfactuur-opvoeren/verkoopfactuur-opvoeren.component";

const rotterdamOracleEbsPluginSpecification: PluginSpecification = {
    pluginId: 'rotterdam-oracle-ebs',
    pluginConfigurationComponent: ConfigurationComponent,
    pluginLogoBase64: ROTTERDAM_ORACLE_EBS_PLUGIN_LOGO_BASE64,
    functionConfigurationComponents: {
        'journaalpost-opvoeren': JournaalpostOpvoerenComponent,
        'verkoopfactuur-opvoeren': VerkoopfactuurOpvoerenComponent,
    },
    pluginTranslations: {
        nl: {
            title: 'Gemeente Rotterdam: Oracle E-Business Suite koppeling',
            description: 'Oracle E-Business Suite plugin voor o.a. het Opvoeren van een Journaalpost',
            'journaalpost-opvoeren': 'Journaalpost opvoeren',
            'verkoopfactuur-opvoeren': 'Verkoopfactuur opvoeren',
            'toggle.yes': 'Ja',
            'toggle.no': 'Nee',
            'configuration.title': 'Configuratienaam',
            'configuration.title.tooltip': 'De naam van de huidige plugin-configuratie. Onder deze naam kan de configuratie in de rest van de applicatie teruggevonden worden.',
            'configuration.title.placeholder': 'Gemeente Rotterdam Oracle EBS Plugin',
            'configuration.baseUrl': 'ESB Url',
            'configuration.baseUrl.tooltip': 'De URL van de Gemeente Rotterdam (Opentunnel) ESB',
            'configuration.mTlsSslContextConfiguration': 'mTLS SSL Context Configuratie',
            'configuration.mTlsSslContextConfiguration.tooltip': 'Selecteer de juiste mTLS SSL Context configuratie die gebruikt moet worden voor authenticatie met de ESB.',
            'configuration.authenticationEnabled': 'Schakel Client Certificate Authenticatie (mTLS SSL) in',
            'configuration.authenticationEnabled.tooltip': 'Deze optie zou alleen op "Nee" moeten staan voor ontwikkeldoeleinden',
            'journaalpost.pvResultVariable': 'Proces variable referentie',
            'journaalpost.pvResultVariable.tooltip': 'Vul hier de naam van de proces variable in waar de Verwerkingsstatus van de journaalpost opvoeren actie in wordt opgeslagen.',
            'journaalpost.procesCode': 'Proces code',
            'journaalpost.procesCode.tooltip': 'Vul hier de process code in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.referentieNummer': 'Referentienummer',
            'journaalpost.referentieNummer.tooltip': 'Vul hier het referentienummer in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.sleutel': 'Sleutel',
            'journaalpost.sleutel.tooltip': 'Vul hier de sleutel in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.boekdatumTijd': 'Boekdatum',
            'journaalpost.boekdatumTijd.tooltip': 'Vul hier de boekdatum in welke voldoet aan de ISO-8601 standaard (bv. 2011-12-03T10:15:30+01:00) Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.categorie': 'Categorie',
            'journaalpost.categorie.tooltip': 'Vul hier de categorie in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.saldoSoort': 'Saldosoort',
            'journaalpost.saldoSoort.tooltip': 'Vul hier de saldo soort in (Budget, Reservering, Werkelijk). Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.omschrijving': 'Omschrijving',
            'journaalpost.omschrijving.tooltip': 'Vul hier de omschrijving in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.grootboek': 'Grootboek',
            'journaalpost.grootboek.tooltip': 'Vul hier het grootboek in (100, R10). Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.boekjaar': 'Boekjaar',
            'journaalpost.boekjaar.tooltip': 'Vul hier het boekjaar in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.boekperiode': 'Boekperiode',
            'journaalpost.boekperiode.tooltip': 'Vul hier de boekperiode in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.viaResolverToggle': 'Dynamische regels via Value resolver',
            'journaalpost.regels': 'Regels',
            'journaalpost.regels.tooltip': 'Voeg minimaal 1 journaalpost regel toe.',
            'journaalpost.regel.toevoegen': 'Regel toevoegen',
            'journaalpost.regel.verwijderen': 'Regel verwijderen',
            'journaalpost.regel.grootboekSleutel': 'Grootboek sleutel',
            'journaalpost.regel.bronSleutel': 'Bron sleutel',
            'journaalpost.regel.boekingType': 'Boekingtype',
            'journaalpost.regel.boekingType.tooltip': 'Vul hier het boeking type in (Credit, Debet). Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.regel.omschrijving': 'Omschrijving',
            'journaalpost.regel.bedrag': 'Bedrag',
            'journaalpost.regel.bronspecifiekeWaarden': 'Bron-specifieke waarden',
            'journaalpost.regel.bronspecifiekeWaarden.tooltip': 'Optionele flex-velden voor bron-specifieke waarden.',
            'journaalpost.regel.bronwaarde.naam': 'Segmentnaam',
            'journaalpost.regel.bronwaarde.waarde': 'Segmentwaarde',
            'journaalpost.regel.bronwaarde.volgorde': 'Volgorde',
            'journaalpost.regel.bronwaarde.toevoegen': 'Bronwaarde toevoegen',
            'journaalpost.regel.bronwaarde.verwijderen': 'Bronwaarde verwijderen',
            'journaalpost.regel.verwijderen.bevestiging': 'Weet u zeker dat u deze regel wilt verwijderen?',
            'journaalpost.regel.bronwaarde.verwijderen.bevestiging': 'Weet u zeker dat u deze bronwaarde wilt verwijderen?',
            'journaalpost.regelsViaResolver': 'Regels (via value resolver)',
            'journaalpost.regelsViaResolver.tooltip': 'Vul hier de naam van de Valtimo value resolver in. Dit is een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'journaalpost.regelsViaResolver.example': 'Voorbeeld van de verwachte gegevensstructuur van de regels',
            'verkoopfactuur.pvResultVariable': 'Proces variable referentie',
            'verkoopfactuur.pvResultVariable.tooltip': 'Vul hier de naam van de proces variable in waar de Verwerkingsstatus van de verkoopfactuur opvoeren actie in wordt opgeslagen.',
            'verkoopfactuur.procesCode': 'Proces code',
            'verkoopfactuur.procesCode.tooltip': 'Vul hier de process code in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.referentieNummer': 'Referentienummer',
            'verkoopfactuur.referentieNummer.tooltip': 'Vul hier het referentienummer in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurKlasse': 'Factuur klasse',
            'verkoopfactuur.factuurKlasse.tooltip': 'Vul hier de factuur klasse in (Creditnota, Debetnota, Correctienota). Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurDatum': 'Factuurdatum',
            'verkoopfactuur.factuurDatum.tooltip': 'Vul hier de factuurdatum in welke voldoet aan de ISO-8601 standaard (bv. 2007-12-03). Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurVervaldatum': 'Factuur vervaldatum',
            'verkoopfactuur.factuurVervaldatum.tooltip': 'Vul hier de factuur vervaldatum in welke voldoet aan de ISO-8601 standaard (bv. 2007-12-03). Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurKenmerk': 'Factuurkenmerk vervaldatum',
            'verkoopfactuur.factuurKenmerk.tooltip': 'Vul hier het factuurkenmerk in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresType': 'Factuuradres type',
            'verkoopfactuur.factuurAdresType.tooltip': 'Selecteer het adres type',
            'verkoopfactuur.factuurAdresType.placeholder': 'Maak een keuze',
            'verkoopfactuur.factuurAdresNaamContactpersoon': 'Naam contactpersoon',
            'verkoopfactuur.factuurAdresNaamContactpersoon.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresVestigingsnummerRotterdam': 'Vestigingsnummer Rotterdam',
            'verkoopfactuur.factuurAdresVestigingsnummerRotterdam.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresStraatnaam': 'Straatnaam',
            'verkoopfactuur.factuurAdresStraatnaam.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresHuisnummer': 'Huisnummer',
            'verkoopfactuur.factuurAdresHuisnummer.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresHuisnummertoevoeging': 'Huisnummertoevoeging',
            'verkoopfactuur.factuurAdresHuisnummertoevoeging.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresPostbus': 'Postbus',
            'verkoopfactuur.factuurAdresPostbus.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresPostcode': 'Postcode',
            'verkoopfactuur.factuurAdresPostcode.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresPlaatsnaam': 'Plaatsnaam',
            'verkoopfactuur.factuurAdresPlaatsnaam.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.factuurAdresLandcode': 'Landcode',
            'verkoopfactuur.factuurAdresLandcode.tooltip': 'Vul hier  in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.inkoopOrderReferentie': 'Inkoop Order Referentie',
            'verkoopfactuur.inkoopOrderReferentie.tooltip': 'Vul hier de inkoop order referentie in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.relatieTypeInfo': 'Het relatie type bepaald of de gegevens voor Achternaam en Voornaam (indien Natuurlijk persoon) of Statutaire naam (indien Niet natuurlijk persoon) verplicht zijn.',
            'verkoopfactuur.relatieType': 'Relatie type',
            'verkoopfactuur.relatieType.tooltip': 'Selecteer het relatie type',
            'verkoopfactuur.relatieType.placeholder': 'Maak een keuze',
            'verkoopfactuur.natuurlijkPersoonBsn': 'Burgerservicenummer (BSN)',
            'verkoopfactuur.natuurlijkPersoonBsn.tooltip': 'Vul hier het burgerservicenummer van de natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.natuurlijkPersoonAchternaam': 'Achternaam',
            'verkoopfactuur.natuurlijkPersoonAchternaam.tooltip': 'Vul hier de achternaam van de natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.natuurlijkPersoonVoornamen': 'Voornamen',
            'verkoopfactuur.natuurlijkPersoonVoornamen.tooltip': 'Vul hier de voornaam/voornamen van de natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonKvkNummer': 'KVK-nummer',
            'verkoopfactuur.nietNatuurlijkPersoonKvkNummer.tooltip': 'Vul hier het KVK-nummer van de niet natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonKvkVestigingsnummer': 'KVK vestigingsnummer',
            'verkoopfactuur.nietNatuurlijkPersoonKvkVestigingsnummer.tooltip': 'Vul hier het KVK vestigingsnummer van de niet natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam': 'Statutaire naam',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam.tooltip': 'Vul hier de statutaire naam van de niet natuurlijke persoon in. Dit kan een vaste waarde zijn maar ook een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.viaResolverToggle': 'Dynamische regels via Value resolver',
            'verkoopfactuur.regels': 'Regels',
            'verkoopfactuur.regels.tooltip': 'Voeg minimaal 1 factuur regel toe.',
            'verkoopfactuur.regel.toevoegen': 'Regel toevoegen',
            'verkoopfactuur.regel.verwijderen': 'Regel verwijderen',
            'verkoopfactuur.regel.hoeveelheid': 'Hoeveelheid',
            'verkoopfactuur.regel.tarief': 'Tarief',
            'verkoopfactuur.regel.btwPercentage': 'BTW percentage',
            'verkoopfactuur.regel.grootboekSleutel': 'Grootboek sleutel',
            'verkoopfactuur.regel.bronSleutel': 'Bron sleutel',
            'verkoopfactuur.regel.omschrijving': 'Omschrijving',
            'verkoopfactuur.regelsViaResolver': 'Regels (via value resolver)',
            'verkoopfactuur.regelsViaResolver.tooltip': 'Vul hier de naam van de Valtimo value resolver in. Dit is een van de Valtimo value-resolvers (case:, doc: of pv:)',
            'verkoopfactuur.regelsViaResolver.example': 'Voorbeeld van de verwachte gegevensstructuur van de regels',
        },
        en: {
            title: 'Municipality of Rotterdam: Oracle E-Business Suite connection',
            description: 'Oracle E-Business Suite plugin for, among other things, entering a journal entry',
            'journaalpost-opvoeren': 'Enter journal entry',
            'verkoopfactuur-opvoeren': 'Enter sales invoice',
            'toggle.yes': 'Yes',
            'toggle.no': 'No',
            'configuration.title': 'Configuration name',
            'configuration.title.tooltip': 'The name of the current plugin configuration. This name can be used to find the configuration throughout the application.',
            'configuration.title.placeholder': 'Gemeente Rotterdam Oracle EBS Plugin',
            'configuration.baseUrl': 'ESB URL',
            'configuration.baseUrl.tooltip': 'The URL of the Gemeente Rotterdam (Opentunnel) ESB',
            'configuration.mTlsSslContextConfiguration': 'mTLS SSL Context Configuration',
            'configuration.mTlsSslContextConfiguration.tooltip': 'Select the correct mTLS SSL Context configuration to be used for authentication with the ESB.',
            'configuration.authenticationEnabled': 'Enable Client Certificate Authenticatie (mTLS SSL)',
            'configuration.authenticationEnabled.tooltip': 'This option should only be "No" for development purposes',
            'journaalpost.pvResultVariable': 'Process variable reference',
            'journaalpost.pvResultVariable.tooltip': 'Enter here the name of the process variable in which the Processing status of the journal entry action is stored.',
            'journaalpost.procesCode': 'Process code',
            'journaalpost.procesCode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.referentieNummer': 'Reference number',
            'journaalpost.referentieNummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.sleutel': 'Key',
            'journaalpost.sleutel.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.boekdatumTijd': 'Booking date',
            'journaalpost.boekdatumTijd.tooltip': 'Should comply with ISO-8601 standard (example 2011-12-03T10:15:30+01:00). This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.categorie': 'Category',
            'journaalpost.categorie.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.saldoSoort': 'Balance type',
            'journaalpost.saldoSoort.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.omschrijving': 'Description',
            'journaalpost.omschrijving.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.grootboek': 'Ledger',
            'journaalpost.grootboek.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.boekjaar': 'Fiscal year',
            'journaalpost.boekjaar.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.boekperiode': 'Accounting period',
            'journaalpost.boekperiode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.viaResolverToggle': 'Dynamic lines via Value resolver',
            'journaalpost.regels': 'Lines',
            'journaalpost.regels.tooltip': 'Add minimal 1 journal entry',
            'journaalpost.regel.toevoegen': 'Add line',
            'journaalpost.regel.verwijderen': 'Remove line',
            'journaalpost.regel.grootboekSleutel': 'General ledger key',
            'journaalpost.regel.bronSleutel': 'Source sleutel',
            'journaalpost.regel.boekingType': 'Booking type',
            'journaalpost.regel.boekingType.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.regel.omschrijving': 'Description',
            'journaalpost.regel.bedrag': 'Amount',
            'journaalpost.regel.bronspecifiekeWaarden': 'Source-specific values',
            'journaalpost.regel.bronspecifiekeWaarden.tooltip': 'Optional flex-fields for source-specific values.',
            'journaalpost.regel.bronwaarde.naam': 'Segment name',
            'journaalpost.regel.bronwaarde.waarde': 'Segment value',
            'journaalpost.regel.bronwaarde.volgorde': 'Order',
            'journaalpost.regel.bronwaarde.toevoegen': 'Add source value',
            'journaalpost.regel.bronwaarde.verwijderen': 'Remove source value',
            'journaalpost.regel.verwijderen.bevestiging': 'Are you sure you want to remove this line?',
            'journaalpost.regel.bronwaarde.verwijderen.bevestiging': 'Are you sure you want to remove this source value?',
            'journaalpost.regelsViaResolver': 'Rules (via value resolver)',
            'journaalpost.regelsViaResolver.tooltip': 'Enter the name of the Valtimo value resolver here. This is one of the Valtimo value resolvers (case:, doc: or pv:)',
            'journaalpost.regelsViaResolver.example': 'Example of the expected data structure of the entries',
            'verkoopfactuur.pvResultVariable': 'Process variable reference',
            'verkoopfactuur.pvResultVariable.tooltip': 'Enter here the name of the process variable in which the Processing status of the sales invoice entry action is stored.',
            'verkoopfactuur.procesCode': 'Process code',
            'verkoopfactuur.procesCode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.referentieNummer': 'Reference number',
            'verkoopfactuur.referentieNummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurKlasse': 'Invoice class',
            'verkoopfactuur.factuurKlasse.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurDatum': 'Invoice date',
            'verkoopfactuur.factuurDatum.tooltip': 'Should comply with ISO-8601 standard (example 2011-12-03). This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurVervaldatum': 'Invoice due date',
            'verkoopfactuur.factuurVervaldatum.tooltip': 'Should comply with ISO-8601 standard (example 2011-12-03). This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurKenmerk': 'Invoice reference',
            'verkoopfactuur.factuurKenmerk.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresType': 'Billing address type',
            'verkoopfactuur.factuurAdresType.tooltip': 'Select the billing address type',
            'verkoopfactuur.factuurAdresType.placeholder': 'Make a choice keuze',
            'verkoopfactuur.factuurAdresNaamContactpersoon': 'Name Contact person',
            'verkoopfactuur.factuurAdresNaamContactpersoon.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresVestigingsnummerRotterdam': 'Rotterdam establishment number',
            'verkoopfactuur.factuurAdresVestigingsnummerRotterdam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresStraatnaam': 'Street name',
            'verkoopfactuur.factuurAdresStraatnaam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresHuisnummer': 'House number',
            'verkoopfactuur.factuurAdresHuisnummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresHuisnummertoevoeging': 'House number addition',
            'verkoopfactuur.factuurAdresHuisnummertoevoeging.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresPostbus': 'PO box',
            'verkoopfactuur.factuurAdresPostbus.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresPostcode': 'Postal code',
            'verkoopfactuur.factuurAdresPostcode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresPlaatsnaam': 'City name',
            'verkoopfactuur.factuurAdresPlaatsnaam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.factuurAdresLandcode': 'Country code',
            'verkoopfactuur.factuurAdresLandcode.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.inkoopOrderReferentie': 'Purchase order reference',
            'verkoopfactuur.inkoopOrderReferentie.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.relatieTypeInfo': 'The relationship type determines whether the data for Surname and First Name (if Natural person) or Statutory name (if Non-natural person) are mandatory.',
            'verkoopfactuur.relatieType': 'Relationship type',
            'verkoopfactuur.relatieType.tooltip': 'Select the relationship type',
            'verkoopfactuur.relatieType.placeholder': 'Make a choice',
            'verkoopfactuur.natuurlijkPersoonBsn': 'Citizen service number (BSN)',
            'verkoopfactuur.natuurlijkPersoonBsn.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.natuurlijkPersoonAchternaam': 'Last name',
            'verkoopfactuur.natuurlijkPersoonAchternaam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.natuurlijkPersoonVoornamen': 'First names',
            'verkoopfactuur.natuurlijkPersoonVoornamen.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonKvkNummer': 'Chamber of Commerce number',
            'verkoopfactuur.nietNatuurlijkPersoonKvkNummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonKvkVestigingsnummer': 'Chamber of Commerce establishment number',
            'verkoopfactuur.nietNatuurlijkPersoonKvkVestigingsnummer.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam': 'Legal name',
            'verkoopfactuur.nietNatuurlijkPersoonStatutaireNaam.tooltip': 'This can be a fixed value but also one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.viaResolverToggle': 'Dynamic rules via Value resolver',
            'verkoopfactuur.regels': 'Entries',
            'verkoopfactuur.regels.tooltip': 'Add minimal 1 sales invoice entry',
            'verkoopfactuur.regel.toevoegen': 'Add entry',
            'verkoopfactuur.regel.verwijderen': 'Remove entry',
            'verkoopfactuur.regel.hoeveelheid': 'Quantity',
            'verkoopfactuur.regel.tarief': 'Rate',
            'verkoopfactuur.regel.btwPercentage': 'VAT percentage',
            'verkoopfactuur.regel.grootboekSleutel': 'General ledger key',
            'verkoopfactuur.regel.bronSleutel': 'Source key',
            'verkoopfactuur.regel.omschrijving': 'Description',
            'verkoopfactuur.regelsViaResolver': 'Rules (via value resolver)',
            'verkoopfactuur.regelsViaResolver.tooltip': 'Enter the name of the Valtimo value resolver here. This is one of the Valtimo value resolvers (case:, doc: or pv:)',
            'verkoopfactuur.regelsViaResolver.example': 'Example of the expected data structure of the entries',
        }
    },
};

export {rotterdamOracleEbsPluginSpecification};
